name: 'action-clang-tidy'
description: 'GitHub Action for clang-tidy'

inputs:
  github_token:
    description: 'GitHub token'
    default: '${{ github.token }}'
  version:
    description: 'Clang version used for testing'
    default: '17'
  workdir:
    description: 'Working directory'
    default: '.'
  builddir:
    description: 'Build directory'
    default: './build'
  tool_name:
    description: 'Tool name display reported in the Pull Request comment'
    default: 'clang-tidy'
  level:
    description: 'Reported level [info,warning,error]'
    default: 'warning'
  reporter:
    description: 'Reviewdog reporter command'
    default: 'github-pr-check'
  filter_mode:
    description: 'Reviewdog filter_mode'
    default: 'nofilter'
  fail_on_error:
    description: 'exit code for reviewdog on error'
    default: 'true'
  reviewdog_flags:
    description: 'extra reviewdog option'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        files: |
          **.c
          **.cpp
          **.h
          **.hpp

    - name: Install clang-tidy-sarif converter
      id: install-clang-tidy-sarif
      shell: bash
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      run: |
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        cargo binstall -y clang-tidy-sarif sarif-fmt

    - name: install reviewdog
      id: install-reviewdog
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      uses: reviewdog/action-setup@v1.1.0

    - name: Install Linux clang dependencies
      id: install-clang-tidy
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      shell: bash
      run: |
        echo "::group::install-clang"
        sudo apt-get update
        # First try installing from default Ubuntu repositories before trying LLVM script
        if ! sudo apt-get install -y clang-tidy-${{ inputs.version }}; then
          # This LLVM script will add the relevant LLVM PPA: https://apt.llvm.org/
          wget https://apt.llvm.org/llvm.sh -O $GITHUB_ACTION_PATH/llvm_install.sh
          chmod +x $GITHUB_ACTION_PATH/llvm_install.sh
          if sudo $GITHUB_ACTION_PATH/llvm_install.sh ${{ inputs.version }}; then
            sudo apt-get install -y clang-tidy-${{ inputs.version }}
          fi
        fi
        echo "::endgroup::"

    # Execute
    - name: Run clang-tidy
      id: run-clang-tidy
      shell: bash
      working-directory: ${{ inputs.workdir }}
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      continue-on-error: true
      run: |
        clang-tidy --list-checks
        clang-tidy -p ./build ${{ steps.changed-files.outputs.all_changed_files }} -- > ${{ inputs.workdir }}/results.txt

    - name: Convert clang-tidy report to sarif
      id: clang-to-sarif
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        clang-tidy-sarif < results.txt > clang_tidy.sarif
        cat clang_tidy.sarif | sarif-fmt --color=always-ansi

    # # - name: Upload SARIF file
    # #   uses: github/codeql-action/upload-sarif@v1
    # #   with:
    # #     sarif_file: clang_tidy.sarif

    - name: reviewdog
      id: reviewdog
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      shell: bash
      working-directory: ${{ inputs.workdir }}
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
      run: |
        reviewdog \
          -name "${{ inputs.tool_name }}" \
          -level "${{ inputs.level }}" \
          -f=sarif \
          -fail-on-error="${{ inputs.fail_on_error }}" \
          -filter-mode="${{ inputs.filter_mode }}" \
          -diff="git diff FETCH_HEAD" \
          -reporter="${{ inputs.reporter }}" \
          ${{ inputs.reviewdog_flags }} \
          < ./clang_tidy.sarif
