name: cpp-lint

on:
  pull_request:

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: CMake
        env:
          CC: clang
        run: |
          cmake -B ./build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          echo "${{ github.workspace }}"

      - name: SAST
        uses: ./.github/actions/cpp-lint/