name: cpp-lint

on:
  push:

jobs:
  cpp-linter:
    runs-on: ubuntu
    permissions:
      pull-requests: write
      issues: write
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          # The following value will only update a single comment
          # in a pull request's thread. Set it to false to disable the comment.
          # Set it to true to post a new comment (and delete the old comment).
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
